### ISSUE TITLE
[Landing page] About us is not clickable 

### ISSUE THREAD

**Issue by AsmaaFailat** [mtahle/CrowdTweet#10]
**Steps to reproduce:**

1. Open this link https://palmycause.info/
2. Click on "About us"

**Actual results:**

1. [Landing page] About us is not clickable 
2. About should be in Arabic as we should have one language for landing page.

<img width="1904" alt="Screen Shot 2023-10-24 at 9 54 18 AM" src="https://github.com/mtahle/CrowdTweet/assets/36152185/8a08d53f-4a17-414f-a0e5-bf81a05fa00e">

**Comment by Abdulhafeez012** [comment]
@AsmaaFailat we will waiting until the content be available to fill it

**Comment by AsmaaFailat** [comment]
Sure from QA perspective we dont keep any non working feature we comment it until then to keep the quality of our product.
