### ISSUE TITLE
[UI Issue][Landing page] Left part of the screen is empty 

### ISSUE THREAD

**Issue by AsmaaFailat** [mtahle/CrowdTweet#15]
**Steps to reproduce:**

1. Open this link https://palmycause.info
2. Check the landing page design 

**Actual results:**
[UI Issue][Landing page] Left part of the screen is empty 

<img width="1904" alt="Screen Shot 2023-10-25 at 3 46 25 PM" src="https://github.com/mtahle/CrowdTweet/assets/36152185/6e28b149-25b5-43f9-b46c-0ba2011b9ef1">

**Comment by Abdulhafeez012** [comment]
@AsmaaFailat the link is change to [staywithpa](https://standwithpalestine.info/home/)

**Comment by AsmaaFailat** [comment]
@Abdulhafeez012 as i cannot delete issue i updated the ticket to different UI issue
