### ISSUE TITLE
[Cancel Auth][Revoke twitter access] Click cancel auth user will redirect to this error "Error: No client verifier has been set."

### ISSUE THREAD

**Issue by AsmaaFailat** [mtahle/CrowdTweet#16]
**Steps to reproduce:**

1. Open this link https://standwithpalestine.info/home/
2. Click "قاوم"
3. Create new twitter account 
4. Give authorization successfully 
5. User will get back to home screen 
6. Click "قاوم" again 
7. Click cancel 
8. Click return to crowdtweet app

**Actual results:**
[UI Issue][Landing page] Click cancel auth user will redirect to this error "Error: No client verifier has been set."

<img width="1904" alt="Screen Shot 2023-10-25 at 4 02 09 PM" src="https://github.com/mtahle/CrowdTweet/assets/36152185/ba89d16b-8b0c-42f9-bfc6-eb466bc70ed0">
<img width="1904" alt="Screen Shot 2023-10-25 at 4 02 31 PM" src="https://github.com/mtahle/CrowdTweet/assets/36152185/b87ab77c-74fb-44c9-9735-1b87c85c60a7">
<img width="1904" alt="Screen Shot 2023-10-25 at 4 03 24 PM" src="https://github.com/mtahle/CrowdTweet/assets/36152185/6ee45c13-6e13-469f-8168-095fca3c96a1">

**Comment by Abdulhafeez012** [comment]
@AsmaaFailat This issue will not shown cause this page will not shown any way
