### ISSUE TITLE
[Enhancement][Landing page] Align title with stats 

### ISSUE THREAD

**Issue by AsmaaFailat** [mtahle/CrowdTweet#36]
[Enhancement][Landing page] Align title with stats 

<img width="648" alt="Screen Shot 2023-10-31 at 3 58 49 PM" src="https://github.com/mtahle/CrowdTweet/assets/36152185/993551bb-23b3-4fa3-abca-6191b0c62a85">

**Comment by rain64x** [comment]
please assign this to me

**Comment by rain64x** [comment]
Hey, this much is done, can push if its good, else requesting suggestions

![2023-10-31_21-34](https://github.com/mtahle/CrowdTweet/assets/48401834/f3bf3af3-580c-47e9-af43-90d8350550ba)

**Comment by rain64x** [comment]
![2023-10-31_21-38](https://github.com/mtahle/CrowdTweet/assets/48401834/978379c4-f100-4e5b-b5eb-88a277da36de)

**Comment by Abdulhafeez012** [comment]
@rain64x it's good you can open a PR

**Comment by rain64x** [comment]
Please check PR #41
