### ISSUE TITLE
[Enhancement] Number of tweet the n should be in capital "N"

### ISSUE THREAD

**Issue by AsmaaFailat** [mtahle/CrowdTweet#37]
[Enhancement] Number of tweet the n should be in capital "N"

<img width="1904" alt="Screen Shot 2023-10-31 at 4 05 45 PM" src="https://github.com/mtahle/CrowdTweet/assets/36152185/59959d36-3bba-4051-a1d3-6f6f2e6e3589">

**Comment by rain64x** [comment]
Please check PR #41
