### ISSUE TITLE
Once user click on "قاوم" user redirect to this error "Token request failed with code 401, response was '{"errors":[{"code":89,"message":"Invalid or expired token."}]}'."

### ISSUE THREAD

**Issue by AsmaaFailat** [mtahle/CrowdTweet#6]
**Steps to reproduce:** 

1. Open this link https://palmycause.info/
2. Click on "قاوم"

**Actual results:**
Once user click on "قاوم" user redirect to this error "Token request failed with code 401, response was '{"errors":[{"code":89,"message":"Invalid or expired token."}]}'."

<img width="1904" alt="Screen Shot 2023-10-23 at 12 26 31 PM" src="https://github.com/mtahle/CrowdTweet/assets/36152185/50a419a5-3360-44b7-94f8-fd336b53d41e">

**Comment by alaalqadi** [comment]
@Abdulhafeez012 i'll open a PR for review

**Comment by alaalqadi** [comment]
@mtahle please deploy this after the PR is merged

**Comment by AsmaaFailat** [comment]
@mtahle i cannot validate as now landing page redirect to 400 
<img width="1904" alt="Screen Shot 2023-10-25 at 8 20 06 AM" src="https://github.com/mtahle/CrowdTweet/assets/36152185/f28cb938-1636-472e-940e-9e91a8d70143">
https://github.com/mtahle/CrowdTweet/issues/15
